// Generated by CoffeeScript 1.3.3
(function() {
  var gprompt, isNode, readline, rl;

  isNode = typeof module !== 'undefined' && module.exports;

  if (isNode) {
    readline = require('readline');
    rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout
    });
  }

  gprompt = function(msg, callback) {
    var answer;
    if (isNode) {
      rl.resume();
      return rl.question(msg, function(answer) {
        rl.pause();
        return callback(answer);
      });
    } else {
      answer = prompt(msg);
      return callback(answer);
    }
  };

  if (isNode) {
    module.exports = gprompt;
  } else {
    this.gprompt = gprompt;
  }

}).call(this);
