// Generated by CoffeeScript 1.3.3
(function() {

  gprompt("What's your name?", function(name) {
    return gprompt("What's your favorite color?", function(color) {
      console.log("Hello, " + name + "!");
      return console.log("You like " + color + ".");
    });
  });

}).call(this);
